tap "anomalyco/tap"
tap "beeftornado/rmtree"

brew "colima"
brew "docker"
brew "docker-compose"
brew "ffmpeg"
brew "fish"
brew "fnm"
brew "gh"
brew "git"
brew "git-lfs"
brew "httpstat"
brew "imagemagick"
brew "lazygit"
brew "neovim"
brew "opencode"
brew "python@3.13"
brew "tree"
brew "wget"

cask "1password"
cask "antinote"
cask "appcleaner"
cask "arc"
cask "autodesk-fusion"
cask "cleanshot"
cask "figma"
cask "firefox"
cask "ghostty"
cask "google-chrome"
cask "itsycal"
cask "linear-linear"
cask "mimestream"
cask "moom"
cask "pocket-casts"
cask "postico"
cask "slack"
cask "spotify"
cask "via"
cask "visual-studio-code"
cask "zoom"


